version: 2
jobs:
  build:
    docker:
       - image: circleci/ruby:2.4.1-node-browsers

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}

      # Database setup
      - run: HANAMI_ENV=test bundle exec hanami db create
      - run: HANAMI_ENV=test bundle exec hanami db migrate

      # run rubocop
      - run:
          name: run lints
          command: |
            bundle exec rubocop

      # run tests!
      - run:
          name: run tests
          command: |
            bundle exec rspec
